/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    java
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation("org.springframework.boot:spring-boot-starter-web:2.1.2.RELEASE")
    implementation("org.springframework.boot:spring-boot-starter-security:2.1.2.RELEASE")
    testImplementation("org.springframework.boot:spring-boot-starter-test:2.1.2.RELEASE")
}

group = "com.shubhamcodes"
version = "0.0.1-SNAPSHOT"
description = "tci-assignment"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}
